version: "3.8"

services:
    backend:
        image: extender777/allchat-backend
        ports:
            - "6000:5000"
        environment:
            - NODE_ENV=production
            - GEMINI_KEY=${GEMINI_KEY}
            - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
            - AWS_SECRET_KEY=${AWS_SECRET_KEY}
            - CLAUDE_KEY=${CLAUDE_KEY}
            - JWT_TOKEN=${JWT_TOKEN}
        restart: unless-stopped
        depends_on:
            - mongodb

    frontend:
        image: extender777/allchat-frontend
        environment:
            - NODE_ENV=production
        ports:
            - "8585:80"
        restart: unless-stopped
        depends_on:
            - backend

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: none

    python-shell:
        image: python:3.12
        volumes:
            - ./python-scripts:/app
        working_dir: /app
        command: ["python", "-u", "shell.py"]
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M
        environment:
            - PYTHONUNBUFFERED=1
        tmpfs:
            - /tmp

volumes:
    mongo-data:
