version: "3.8"
services:
    backend:
        image: my-backend
        ports:
            - "6000:5000"
        environment:
            - GOOGLE_KEY=${GOOGLE_KEY}
    frontend:
        image: my-frontend
        ports:
            - "8585:80"
        depends_on:
            - backend
