table_manager:
    retention_deletes_enabled: true
    retention_period: 720h

querier:
    max_concurrent: 120 # Increase from the default

limits_config:
    max_outstanding_requests_per_tenant: 4048 # Increase if needed
